Suggestion to just have one class to upload files
algorand/mule pull request #24
Opened 2020-05-14 20:00 UTC by btoll

2020-05-15 14:01 UTC, egieseke commented on mule/task/s3/__init__.py
> +        if self.objectName or self.filename:
Is this a potential error condition if the output file name is provided, but the object name is not?

2020-05-15 16:35 UTC, btoll commented on mule/task/s3/__init__.py
> +        if self.objectName or self.filename:
I just tested and no error, it looks ok.

2020-05-15 16:36 UTC, btoll commented on mule/task/s3/__init__.py
> +        if self.objectName or self.filename:
I just tested and no error, it looks ok.

2020-05-19 15:42 UTC, egieseke commented on mule/task/s3/__init__.py
> +        if self.objectName or self.filename:
Should you raise an error in this case? since the assumption is that there is one and only one object to download into the specified file name.

2020-05-19 15:54 UTC, btoll commented on mule/task/s3/__init__.py
> +        if self.objectName or self.filename:
There are a couple of ways to download files:
1. Specify a file either as an object name or a filename.
1. If there is no #1, a prefix and/or suffix is expected.

I think you're right, there should be an exception raised if none of those conditions are met.  I'll add one.

2020-05-19 16:44 UTC, bricerisingalgorand commented on mule/task/s3/__init__.py
>          self.prefix = args['prefix']
it looks like prefix was removed from the required fields list

2020-05-19 16:45 UTC, bricerisingalgorand commented on mule/task/s3/__init__.py
>  class DownloadFile(ITask):
I think if we're going to make this change, this needs to be renamed to just Download possibly. DownloadFile doesn't make sense if it will download 1 or many files

2020-05-19 16:46 UTC, btoll commented on mule/task/s3/__init__.py
>          self.prefix = args['prefix']
That was a mistake, correcting.

2020-05-19 16:48 UTC, bricerisingalgorand commented on mule/task/s3/__init__.py
> +        if self.objectName or self.fileName:
We'll need some handling around when a fileName is set but no objectName

2020-05-19 16:49 UTC, bricerisingalgorand commented on mule/util/s3_util.py
> +def download_files(bucket_name: str, object_name: str, prefix: object = "", suffix: object = "", output_dir: str = ".") -> bool:
I'm confused, isn't this a syntax error? The header doesn't match the call from the s3 mule task. This param isn't necessary right?

2020-05-19 16:50 UTC, bricerisingalgorand commented on mule/task/s3/__init__.py
>  class UploadFile(ITask):
Same comment as the DownloadFile name, but this would probably need to be Upload instead also

2020-05-19 16:52 UTC, btoll commented on mule/task/s3/__init__.py
>  class DownloadFile(ITask):
Will change.

2020-05-19 16:53 UTC, btoll commented on mule/task/s3/__init__.py
> +        if self.objectName or self.fileName:
Yes, I'm adding that now.

2020-05-19 16:53 UTC, btoll commented on mule/task/s3/__init__.py
>  class UploadFile(ITask):
Will change.

2020-05-19 16:55 UTC, btoll commented on mule/util/s3_util.py
> +def download_files(bucket_name: str, object_name: str, prefix: object = "", suffix: object = "", output_dir: str = ".") -> bool:
Probably.  Initially, this PR was a draft and intended to open a discussion on this.  I threw this into the signature just to have something there, but I'll look more closely at it now.

2020-05-19 17:45 UTC, btoll commented on mule/task/s3/__init__.py
> +        if self.objectName or self.fileName:
Actually, it looks as though this should be an `or` situation.  The `objectName` is the full key name of the object to download, so both options wouldn't need to be set.

2020-05-19 18:04 UTC, btoll commented on mule/util/s3_util.py
> +def download_files(bucket_name: str, object_name: str, prefix: object = "", suffix: object = "", output_dir: str = ".") -> bool:
Fixed

2020-05-19 18:53 UTC, algojohnlee commented
Looks good to me, yay simpler

2020-05-19 19:09 UTC, onetechnical submitted a review, later dismissed
Looks good to me, yay simpler

2020-05-19 20:51 UTC, bricerisingalgorand commented on mule/task/s3/__init__.py
> +        if self.objectName or self.fileName:
but what about when someone uses these configurations

```yaml
- task: s3.Download
  bucket: mybucket
  prefix: myprefix
  fileName: test.jpg
```

s3_util.download_file will get called with an objectName of none and throw an exception right?

2020-05-19 20:51 UTC, egieseke commented on mule/task/s3/__init__.py
> +        if self.objectName or self.filename:
Did you want to add an exception in case the object name was not specified?

2020-05-19 20:56 UTC, bricerisingalgorand requested changes

2020-05-19 20:56 UTC, bricerisingalgorand commented on mule/task/s3/__init__.py
> +            raise MissingOption('objectName or fileName must be specified')
objectName and fileName aren't listed as required fields, so why are you raising this exception here? Also you're not handling the basic happy path situation of just the required fields being set

2020-05-19 20:56 UTC, bricerisingalgorand commented on mule/task/s3/__init__.py
> +            raise MissingOption('objectName or fileName must be specified')
This else could probably handle the basic happy path case.

2020-05-19 22:33 UTC, btoll commented on mule/task/s3/__init__.py
> +            raise MissingOption('objectName or fileName must be specified')
They can't be listed as required fields because files can be downloaded by only specifying `prefix` and `suffix`.  Also, isn't `suffix` necessary as well if not specifying either `fileName` or `objectName`?

I think what you're hitting on is that this API is a bit confusing and that's a legitimate criticism, since files can be downloaded in more than one way.

2020-05-19 22:35 UTC, btoll commented on mule/task/s3/__init__.py
> +        if self.objectName or self.fileName:
I see what you're saying.  Yes, I'll fix that.

2020-05-19 22:41 UTC, btoll commented on mule/task/s3/__init__.py
> +        if self.objectName or self.filename:
I don't think so, because a `fileName` is the only field needed to download a file (along with `prefix`, which is required).

If both were specified, which would win?

2020-05-19 22:46 UTC, btoll commented on mule/task/s3/__init__.py
> +        if self.objectName or self.filename:
Ah, nevermind that last comment.  I misunderstood the filename to be the name of the file that was wanted to be downloaded.

I'll fix that.

2020-05-19 23:46 UTC, egieseke approved these changes
Looks good.

2020-05-20 16:26 UTC, closed without merging