Add support for parameterized go version
algorand/mule pull request #34
Opened 2020-06-18 21:15 UTC by egieseke

Updated mule to support a parametrized go version.  The go version is now included in the docker image tag.

2020-06-18 22:35 UTC, btoll commented on mule/task/shell/docker.py
> +        'goVersion'
I would rather have the version default to something reasonable rather than enforcing it as a param.

2020-06-18 22:36 UTC, btoll commented on mule/task/shell/__init__.py
> +        return super().execute(job_context)
Should this code be in another commit?  It seems out of scope.

2020-06-18 22:48 UTC, btoll commented on mule/task/shell/__init__.py
> +        return super().execute(job_context)
That question is for all the new code in that file.

2020-06-19 13:30 UTC, egieseke commented on mule/task/shell/docker.py
> +        'goVersion'
We want to make sure that it is specified for now.

2020-06-19 13:31 UTC, egieseke commented on mule/task/shell/__init__.py
> +        return super().execute(job_context)
These changes are required to return the output of the get_golang_version.sh script.

2020-06-19 16:10 UTC, btoll commented on mule/task/shell/docker.py
> +        'goVersion'
What if myself or another developer has a Dockerfile that doesn't care about go?

2020-06-19 16:11 UTC, btoll commented on mule/task/shell/__init__.py
> +        return super().execute(job_context)
But what about the new `save_logs` option?

2020-06-19 16:17 UTC, btoll commented on mule/task/shell/docker.py
> +        'goVersion'
This is also a breaking change.  All the yaml files will need to be updated, which means anyone using this will find that there process is broken.

2020-06-19 16:42 UTC, egieseke commented on mule/task/shell/__init__.py
> +        return super().execute(job_context)
That is also required to fetch the go version.

2020-06-19 17:20 UTC, btoll commented on mule/task/shell/__init__.py
> +        return super().execute(job_context)
It would be nice to have an example in the PR description that shows how this is used.  I'm assuming from your draft PR here https://github.com/algorand/go-algorand/pull/1185 that this is what it would look like:
```
  - task: shell.docker.Ensure
    name: alpine
    image: algorand/go-algorand-ci-linux
    version: '{{ docker.Version.outputs.version }}-{{ shell.Shell.go-version.outputs.logs }}'
    goVersion: '{{ shell.Shell.go-version.outputs.logs }}'
    dockerFilePath: docker/build/cicd.alpine.Dockerfile
    dependencies: shell.Shell.go-version docker.Version
```
My thoughts on that are that:
- It would be great to not have that as a required param.
- It would be simpler just to specify the version as `goVersion: 1.14` or whatever.
- It seems that the `save_logs` option is just for accessing the go version, not as a general "get all my logs" as the name implies?  If this were to be kept, would it be better to name it `{{ shell.Shell.go-version.outputs.goVersion }`?

2020-06-23 20:27 UTC, bricerisingalgorand commented on mule/task/shell/__init__.py
> +        return super().execute(job_context)
The reason a script is setting the go version is because the travis pipeline needs to determine which go version to use as well. Also, using this script we can determine what version of go to use from the respective field in the go.mod file in order to test on the minimum version we're supporting

2020-06-23 20:36 UTC, bricerisingalgorand commented on mule/task/shell/__init__.py
> +        return super().execute(job_context)
The reason we want to use a script is so that we can get the go version from the go.mod file that declares the lowest version our project is compatible with. Also, the travis job needs to know the go version as well, so using a script both travis and mule can get the go version from the same place

2020-06-23 23:22 UTC, egieseke commented on mule/task/shell/docker.py
> +        'goVersion'
OK, made goVersion optional.

2020-06-24 01:13 UTC, btoll commented on mule/task/shell/docker.py
> +        'goVersion'
Great, thanks.

2020-06-24 13:47 UTC, bricerisingalgorand submitted a review, later dismissed

2020-06-24 19:01 UTC, btoll commented on mule/task/shell/__init__.py
> +        return super().execute(job_context)
It'd be good to have the output be more general.  How about we capture all the data and have it as an object:
```
shell.Shell.go-version.outputs.logs {}
```

2020-06-25 13:56 UTC, onetechnical submitted a review, later dismissed
I approve of this, with a caveat. The goVersion handling here is tightly coupled to docker implementation, which makes it less of a general use case and more of a specific use case. We should refactor to be more independent, because I don't like forcing this to be go-specific. Can you create a ticket for that?

2020-06-25 13:56 UTC, onetechnical commented on mule/task/shell/__init__.py
> +        return super().execute(job_context)
I think that would imply an opinionated output from an arbitrary shell command. I think I'd prefer output or something, as "logs" have other connotations. (This makes for an ugly outputs.output, but I can't think of a better option.)

2020-06-26 14:41 UTC, btoll commented on mule/task/shell/__init__.py
> +        return super().execute(job_context)
My thought is that it would be ok to have all of the params that were passed available if needed or wanted in a `logs` object, and this could simply access what it needs via `logs.goVersion`.

As your comment below mentions, the fixes and features that I'm seeing are addressing specific use cases that we may need internally, but we really need to be thinking about this more as a framework.

2020-06-26 15:33 UTC, btoll commented
This ticket should be linked with this one, as it's using the goVersion log that's implemented here: https://github.com/algorand/go-algorand/pull/1185/

2020-06-26 16:48 UTC, btoll requested changes
I'm going to block this for a couple of reasons.
1.  I had raised a question the end of last week about how this is returning its "log" information, but I don't feel that it's been sufficiently addressed.  I understand that the current approach works, but I don't feel that it's sufficient.
2.  The other PR that I linked to is relying syntactically on this approach, so if we don't fix this now it will create more churn than just in the `mule` repo.

2020-06-26 17:12 UTC, bricerisingalgorand commented on mule/task/shell/__init__.py
> +        return super().execute(job_context)
I don't think I understand. What data are you looking for from a shell command other than the logs?

As far as task inputs go, those are available for every task already using `task_id.inputs.field_name`

2020-06-26 19:30 UTC, btoll commented on mule/task/shell/__init__.py
> +        return super().execute(job_context)
My presumption was that this added the ability to pass any number of commands that would then be available in an object (I thought `logs` was that object).  Now I also understand John's comment as well.

I must admit I'm not crazy about this approach.  It seems bolted on just to make this use case work.

If you want more data from commands to be available to subsequent processes, currently you'll have to write them one after the other, which further increases the size of these yaml files.  Also, it increases the number of tasks that need to be added to another one's dependency config.

2020-06-29 17:17 UTC, bricerisingalgorand commented on mule/task/shell/__init__.py
> +        return super().execute(job_context)
But what more data are you looking for?

It's ok that you want more features out of the `shell.Shell` task, but right now all we need is a way to use logs from scripts that task has executed. If we want that task to support executing multiple shell commands, we can either make a story for implementing that feature or work on a story that requires it.

2020-06-29 19:48 UTC, btoll commented on mule/task/shell/__init__.py
> +        return super().execute(job_context)
I'm saying the opposite, actually.  I don't think adding more functionality to the `shell.Shell` task is a good idea, it's just a way of quickly getting this to work.

If this is to be refactored to also return the output of the command, I would think the next question to be asked is what if I need to capture the output of multiple commands?  That would cut down on the size of the yaml file, which is something I hope we're all concerned about.

Since this is new functionality, I think it's reasonable to ask that question now and possibly accomodate that approach rather than kicking that can down the line.

In the meantime, I think a simple improvement would be the naming.  For example, call it `stdout` instead of `logs`, which is more descriptive of what is being captured.  So, the output could be referenced like:
```
shell.Shell.go-version.outputs.stdout
```
Also, maybe just always return it, that way it saves the user from having to explicit specify they want.

2020-06-29 19:58 UTC, onetechnical commented on mule/task/shell/__init__.py
> +        return super().execute(job_context)
I like the idea of using stdout instead of logs. I'm not sure I understand the multiple command bit; would we pass it an array of arrays of commands or something?

2020-06-29 20:44 UTC, bricerisingalgorand commented on mule/task/shell/__init__.py
> +        return super().execute(job_context)
Supporting always printing script logs and storing them would be difficult because the process outputs are appended to IO streams. This means that in order to do that we would need to manage our own stream and handle frequent forwarding to stdout ourselves. We don't have a use case here where that is necessary, so that's another thing we should probably make another story if we actually need that. We can go ahead and rename the field to stdout though, and include stderr while we're at it

2020-06-29 21:18 UTC, egieseke commented on mule/task/shell/__init__.py
> +        return super().execute(job_context)
Split return of IShellTask.execute into 3 parts for `stdout`, `stderr`, and `returncode`.  All can be accessed by the caller.

2020-06-29 21:44 UTC, btoll commented on mule/task/shell/__init__.py
> +        return super().execute(job_context)
Sounds good, thanks guys.

2020-06-29 21:46 UTC, btoll approved these changes

2020-06-29 21:48 UTC, onetechnical approved these changes
I like the change!

2020-06-29 21:51 UTC, btoll commented
@onetechnical Yes, multiple commands could look something like this:
```
  - task: shell.Shell
    name: foo
    command:
      -./get_golang_version.sh
      -./foo.sh
      -./bar.sh
```
rather than
```
  - task: shell.Shell
    name: golang
    command: ./get_golang_version.sh

  - task: shell.Shell
    name: foo
    command: ./foo.sh

  - task: shell.Shell
    name: bar
    command: ./bar.sh
```

2020-06-30 20:57 UTC, merged