Add test suite for public API
algorand/mule pull request #66
Opened 2021-01-08 05:36 UTC by btoll

## Summary

Added test suite for public API.

## Test Plan

`pytest`

2021-01-15 19:12 UTC, onetechnical requested changes
Some thoughts on this. I'd prefer to dig out some of the go-algorand-specific stuff from the test suite.

2021-01-15 19:12 UTC, onetechnical commented on tests/mule.yaml
> +    version: scripts/configure_dev-deps.sh
These tests are very algorand-specific. We should probably make general use case tests.

2021-01-15 19:12 UTC, onetechnical commented on tests/mule.yaml
> +#      - VERSION=$VERSION
Nit: remove comment

2021-01-15 19:12 UTC, onetechnical commented on mule/main.py
> +    agents = []
Was the absence of this a bug?

2021-01-15 19:12 UTC, onetechnical commented on tests/test_mule.py
> +        assert agent_keys == set(["NETWORK", "VERSION"])
Hmm, as noted above, I'm not wild about putting go-algorand-specific details into here. Maybe shorten and generify them in the test config?

2021-01-15 19:24 UTC, btoll commented on mule/main.py
> +    agents = []
Yes

2021-01-15 19:24 UTC, btoll commented on tests/test_mule.py
> +        assert agent_keys == set(["NETWORK", "VERSION"])
Will do.

2021-01-15 19:24 UTC, btoll commented on tests/mule.yaml
> +#      - VERSION=$VERSION
Will do.

2021-01-15 19:25 UTC, btoll commented on tests/mule.yaml
> +    version: scripts/configure_dev-deps.sh
I'll remove the algorand mentions.

2021-01-16 22:21 UTC, btoll commented on tests/mule.yaml
> +    version: scripts/configure_dev-deps.sh
Actually, looking at this more closely, it will be a lot of work to remove the algorand bits.  We'll either need to push up new images that will then be referenced from this yaml (and that will still have "algorand" it it as it would be in one of our docker repos) or it will have to be built on-the-fly every time, which will add considerable time to running the tests.

It's not leaking any sensitive information, too.  These images are publicly-available.

2021-01-16 22:22 UTC, btoll commented on tests/test_mule.py
> +        assert agent_keys == set(["NETWORK", "VERSION"])
All of this is public information, both visible in s3 and on github.

2021-01-16 22:23 UTC, btoll commented on mule/main.py
> +    agents = []
Done

2021-01-16 22:24 UTC, btoll commented on tests/mule.yaml
> +#      - VERSION=$VERSION
Done

2021-01-19 00:15 UTC, onetechnical approved these changes, later dismissed
I'm going to mark this as approved because the core of it seems fine, but it does feel like we're testing the algorand implementaiton (with the algorand-specific bits) than mule itself, which may be confusing to third parties.

2021-01-19 00:15 UTC, onetechnical commented on tests/mule.yaml
> +    version: scripts/configure_dev-deps.sh
I'm not as concerned with information leakage here as that it's a super-specific use case for mule that people outside of our company wouldn't understand.

2021-01-19 00:15 UTC, onetechnical commented on tests/test_mule.py
> +        assert agent_keys == set(["NETWORK", "VERSION"])
As before - seems like it's testing our specific algorand implementation, not testing mule itself, which is why it rings odd to me.

2021-01-19 00:44 UTC, btoll commented on tests/test_mule.py
> +        assert agent_keys == set(["NETWORK", "VERSION"])
How is it not testing mule?

2021-01-19 00:44 UTC, btoll commented on tests/mule.yaml
> +    version: scripts/configure_dev-deps.sh
How is it super-specific?

2021-01-20 18:40 UTC, egieseke commented on tests/mule.yaml
> +    version: scripts/configure_dev-deps.sh
I agree that the test should be independent of algorand, since Mule is intended to be a generic pipeline utility.

2021-01-20 18:42 UTC, btoll commented on tests/mule.yaml
> +    version: scripts/configure_dev-deps.sh
Again, how is this super-specific?  Can either one of you elaborate?

2021-01-20 18:42 UTC, egieseke reviewed
Try to make test generic.  We can add additional test to go-algorand-ci that test using mule for the algorand pipeline.

2021-01-20 18:42 UTC, egieseke commented on tests/test_mule.py
> +        assert agent_keys == set(["NETWORK", "VERSION"])
It would be best to structure the mule tests to not depend on algorand specifics.

2021-01-20 18:43 UTC, btoll commented
> Try to make test generic. We can add additional test to go-algorand-ci that test using mule for the algorand pipeline.

Again, it would be helpful if either one of you can elaborate on how these tests aren't general.

2021-01-20 19:01 UTC, egieseke commented on tests/mule.yaml
> +    version: scripts/configure_dev-deps.sh
this reference for example: `image: algorand/go-algorand-ci-linux-ubuntu`

2021-01-20 19:53 UTC, btoll commented on tests/mule.yaml
> +    version: scripts/configure_dev-deps.sh
But that's just a publicly-available image.  We could test any image.  I chose this because there's a good chance we already have that cached.

You want to look at how the public API is being tested, which is completely independent of the image used.

2021-01-20 19:56 UTC, btoll commented on tests/mule.yaml
> +    version: scripts/configure_dev-deps.sh
I did address this in one of my previous comments on this thread.

2021-01-20 20:29 UTC, btoll commented on tests/mule.yaml
> +    version: scripts/configure_dev-deps.sh
Also, the way that `mule` was designed makes it difficult to use just any generic image without having knowledge of the way the project was structured.

This ticket will address that: https://github.com/algorand/go-algorand-internal/issues/951

2021-01-21 16:26 UTC, onetechnical commented on tests/mule.yaml
> +    version: scripts/configure_dev-deps.sh
The entire agent config is very algorand-specific. This isn't a hiding information thing, it's test case thing. I believe the test is that we set an env in the agent, so stripping down the agent to a simple docker container with an env of like ENV_VAR_1 and ENV_VAR_2 would be more readily understandable.

2021-01-21 18:22 UTC, egieseke submitted a review, later dismissed

2021-01-21 23:11 UTC, onetechnical approved these changes
I think this is fine for now, because it's testing the core thing we want (env var from agent).

For the test case I probably would have fabricated something simpler to be more explicit, (like maybe use the hello-world docker agent and pass an env there?). Otherwise people might think NETWORK and VERSION are special variables we're testing against.

2021-01-21 23:43 UTC, bricerisingalgorand approved these changes

2021-01-21 23:44 UTC, merged