Added pre-commit hooks
algorand/mule pull request #68
Opened 2021-01-12 05:14 UTC by btoll

## Summary

Added two git pre-commit hooks.  One is for `pytest` for the unit tests and the other is for `pycodestyle`, a PEP8 linter.  Installing is not mandatory, but it's a nice-to-have.

If installed, the git hooks can be bypassed when committing (for instance, in the case that there are too many linter warnings):
```
git commit --no-verify
```

2021-01-12 17:52 UTC, btoll commented
This is an easy way to run tests: https://github.com/algorand/mule/pull/65

2021-01-15 19:00 UTC, onetechnical requested changes
Mostly want to ensure we have documentation around this.

Did we decide we wanted to enforce PEP8? I'm not 100% on this yet; I don't like the tabbing recommendation, but that's just me. Haven't reviewed the rest of it yet.

2021-01-15 19:00 UTC, onetechnical commented on scripts/hooks/install.sh
> +git config --global --add hooks.pre-commit.mule "pytest.sh"
Should these be global? 🤔

2021-01-15 19:00 UTC, onetechnical commented on scripts/hooks/pre-commit.d/pycodestyle.sh
> +if ! which pycodestyle > /dev/null
We should add a recommendation to install pycodestyle and pytest to the README.

2021-01-15 19:00 UTC, onetechnical commented on scripts/hooks/pre-commit.d/pytest.sh
> +    cd tests || exit
Also add a note about how to write tests to the README.

2021-01-15 19:22 UTC, btoll commented on scripts/hooks/pre-commit.d/pytest.sh
> +    cd tests || exit
There's lots of good documentation about `pytest` out there.

2021-01-15 19:23 UTC, btoll commented
> Mostly want to ensure we have documentation around this.
> 
> Did we decide we wanted to enforce PEP8? I'm not 100% on this yet; I don't like the tabbing recommendation, but that's just me. Haven't reviewed the rest of it yet.

My feeling is that this is an easy win for those who want to add the hooks.  It's optional, so it won't be enforcing anything.

We've been talking about adding these checks for a while, I wanted to act on it in a way that's unobtrusive.

2021-01-17 17:42 UTC, btoll commented on scripts/hooks/install.sh
> +git config --global --add hooks.pre-commit.mule "pytest.sh"
Good idea, I changed to local (`.git/config`).

2021-01-17 17:54 UTC, btoll commented on scripts/hooks/pre-commit.d/pycodestyle.sh
> +if ! which pycodestyle > /dev/null
Updated README.

2021-01-19 00:08 UTC, onetechnical approved these changes

2021-01-22 19:19 UTC, egieseke approved these changes

2021-01-22 20:31 UTC, merged