Fix error message for .muleci.yml not found
algorand/mule pull request #72
Opened 2021-02-12 18:50 UTC by bricerisingalgorand

2021-02-12 18:51 UTC, onetechnical requested changes

2021-02-12 18:51 UTC, onetechnical commented on mule/ci/driver.py
> +        raise Exception(f"Application name must be provided through cli arguement or {config.MULE_FILE_PATH} file")
```suggestion
        raise Exception(f"Application name must be provided through cli argument or {config.MULE_FILE_PATH} file")
```

2021-02-12 19:16 UTC, onetechnical approved these changes

2021-02-16 15:07 UTC, algobarb approved these changes

2021-02-16 15:16 UTC, egieseke approved these changes

2021-02-18 14:33 UTC, merged