Update github engineering template
algorand/mule pull request #77
Opened 2021-07-15 16:12 UTC by algojack

## Summary

Update github engineering template
## Test Plan

Previewed

2021-07-19 19:29 UTC, algojack commented on .github/ISSUE_TEMPLATE/feature_request.md
> -https://www.algorand.com/resources/blog/security
@onetechnical is it ok that we are getting rid of security message? and also "algo -d" instead of "mule --version" above?

2021-07-21 12:46 UTC, onetechnical commented on .github/ISSUE_TEMPLATE/feature_request.md
> -https://www.algorand.com/resources/blog/security
I'd leave the security message, but the change to the command is a good idea.

2021-07-21 15:03 UTC, algojack commented on .github/ISSUE_TEMPLATE/feature_request.md
> -https://www.algorand.com/resources/blog/security
updated

2021-07-21 15:13 UTC, onetechnical requested changes

2021-07-21 15:13 UTC, onetechnical commented on .github/ISSUE_TEMPLATE/bug_report.md
> +* Node status if applicable: `goal node status`
I would just delete this line altogether. You could be using mule in a context completely separate from algod.

2021-07-21 15:47 UTC, algojack commented on .github/ISSUE_TEMPLATE/bug_report.md
> +* Node status if applicable: `goal node status`
removed that line

2021-07-21 16:57 UTC, onetechnical approved these changes

2021-07-21 19:44 UTC, algobarb approved these changes

2021-07-21 19:47 UTC, merged